defaultProject: ringed-hallway-427106-i4
defaultLocation: us-central1
defaultDataset: presentation_dataset
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0-beta.4
vars:
    orderdate: '2024-06-01'
    City: 'Chennai'
    StartDate: '2024-01-01'
    EndDate: '2024-12-31'